//
//  LamborginiData.swift
//  Lamborghini
//
//  Created by bastien giat on 02/04/2021.
//

import SwiftUI

var lamborghiniData: [Lamborghini] = [
    Lamborghini(name: "Aventador", image: "aventador", description: "Supercar remplaçante de la Murciélago. Elle affiche une puissance de 700ch et un 0 à 100km/h en 2,9 secondes. \n\nL'Aventador a été en mesure d'abattre le kilomètre départ arrêté en moins de 20 secondes (19,3 secondes). Dans l'émission britannique Top Gear, l'Aventador de Jeremy Clarkson a été poussée à 328,6 km/h sur le circuit de Nardò. \n\nL'Aventador s'annonce donc comme la plus performante des Lamborghini (elle a depuis cependant été surpassée par la Centenario de 770 ch).", releaseDate: "2011", price: 335865, gallery: ["aventador-1", "aventador-2", "aventador-3"]),
    Lamborghini(name: "Urus", image: "urus", description: "Tout premier SUV de la marque du taureau. \n\nLamborghini entre ainsi dans le cercle des constructeurs de luxe qui ont ajouté un SUV dans leur gamme, comme Porsche avec le Cayenne, Maserati et le Levante et Bentley avec le Bentayga. \n\nLe constructeur au taureau décrit son véhicule comme un SSUV (Super Sports Utility Vehicle)7, avec « des performances sans précédent » confie Stefano Domenicali, PDG de la marque.", releaseDate: "4 décembre 2017", price: 205715, gallery: ["urus-1", "urus-2", "urus-3", "urus-4"]),
    Lamborghini(name: "Huracan", image: "huracan", description: "Succède à la Gallardo en utilisant un moteur V10 de 5,2 litres développant 610ch. Le nom « Huracán » (littéralement « ouragan ») vient du nom d'un taureau de combat espagnol.  \n\nLe 13 mars 2018, Lamborghini annonce avoir atteint la production de 10 000 exemplaires d'Huracán. \nElle est ainsi le second modèle le plus vendu de l'histoire de Lamborghini derrière son aînée la Gallardo.", releaseDate: "2014", price: 180000, gallery: ["huracan-1", "huracan-2", "huracan-3", "huracan-4"]),
    Lamborghini(name: "Sian", image: "sian", description: "Supercar hybride produite seulement à 63 exemplaires. \n\nSon nom ne fait pas référence à un taureau comme les autres modèles mais veut dire éclair. 63 exemplaires pour un hommage à l'année de naissance de la marque. \n\nLa Sián repose sur la base de son aînée la plus sportive, la Lamborghini Aventador, et pèse 1 620 kg soit 34 kg de plus avec son système hybride. La supercar à hybridation légère 48 Volts de Lamborghini est motorisée par le 12-cylindres de 6,5 L de l'Aventador SVJ, doté ici de soupapes d'admission en titane et poussé à 785 ch (à 8 500 tr/min). \nIl est accouplé à la boîte de vitesses ISR (Independent Shifting Rods) à sept rapports avec un différentiel arrière mécanique autobloquant.", releaseDate: "4 septembre 2019", price: 3300000, gallery: ["sian-1", "sian-2", "sian-3", "sian-4"]),
    Lamborghini(name: "Terzo Millennio", image: "terzoMillennio", description: "Concept car de supercar électrique. \nElle a pour but de rechercher des solutions techniques pour une future Lamborghini plus respectueuse de l'environnement. Lamborghini décrit son concept-car de « très, très visionnaire » et qu'il représente « une vision de la future voiture de sport Lamborghini dans une, deux ou trois générations » selon Mitja Borkert, le chef du design du Centro Stile Lamborghini. \n\nLe concept est équipé de quatre moteurs électriques, un dans chaque roue, alimentés par des supercondensateurs installés sur les panneaux de carrosserie, dans des micro-tubes. Ceux-ci permettent à la Terzo Millennio de se passer de batterie pour le stockage d'énergie. \n\nLa carrosserie de la Terzo Millennio est en fibre de carbone qui, selon Lamborghini, permettrait de stocker de l’énergie électrique, mais aurait aussi la faculté de se régénérer partiellement en cas de choc grâce aux nano-charges électriques contenu dans le fluides des micro-tubes.", releaseDate: "6 novembre 2017", price: 232285, gallery: ["terzoMillennio-1", "terzoMillennio-2", "terzoMillennio-3", "terzoMillennio-4"]),
    Lamborghini(name: "Centenario", image: "centenario", description: "Elle marque le centième anniversaire du fondateur de la marque, Ferruccio Lamborghini (1916-1993). Fusion de la Veneno et de l'aventador. \n\nPrésentée au Salon de Genève 2016, elle affiche une puissance de 770 ch avec un 0 à 100 km/h en 2.8 secondes et une distance de freinage 100-0 km/h de 30 mètres. Cette Lamborghini peut atteindre les 350 km/h, bien plus que la Lamborghini Aventador qui a été poussée à 329 km/h par Jeremy Clarkson. \n\nElle est produite à raison de 40 exemplaires, 20 coupés et 20 roadsters.", releaseDate: "1er mars 2016", price: 2500000, gallery: ["centenario-1", "centenario-2", "centenario-3", "centenario-4"])

]
